name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Specify the release version, e.g., 1.2.3 (Do not prefix with 'v')
        required: true
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  RUST: 1.82

jobs:
  # build-test:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-24.04, macos-15, windows-2022]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Rust
  #       run: |
  #         rustup default ${{ env.RUST }}
  #         rustup component add clippy

  #     - name: Build Rust Project
  #       run: cargo build --manifest-path=./Cargo.toml --release

  #     - name: Test Rust Project
  #       run: cargo test --manifest-path=./Cargo.toml --release

  release:
    name: Release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    environment: release
    # needs:
    #   - build-test
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Rust
        run: |
          rustup default ${{ env.RUST }}
          rustup component add clippy        

      - name: Determine Tag
        id: get-tag
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          else
            echo "tag=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Create a GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.tag }}
          name: Release v${{ env.tag }}

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: >
          cargo publish
          --verbose
          --locked
          --dry-run
